#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Do we run dovecot?
if [ "${POSTFIX_SASL_AUTH}" = "true" ]; then
    s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "/usr/local/bin/check_dovecot.sh" \
        /usr/sbin/dovecot -c /etc/dovecot/dovecot.conf -F \
        2>&1 | awk -W Interactive '{print "[dovecot] " $0}'
else
    sleep 86400
    exit 0
fi
