#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

# Wait for opendkim
if [ "${ENABLE_OPENDKIM}" = "true" ]; then
    echo "[postfix] Waiting for opendkim..."
    s6-svwait -U /run/s6/services/opendkim
fi

# Wait for postgrey
if [ "${ENABLE_POSTGREY}" = "true" ]; then
    echo "[postfix] Waiting for postgrey..."
    s6-svwait -U /run/s6/services/postgrey
fi

# Wait for Dovecot
if [ "${POSTFIX_SASL_AUTH}" = "true" ]; then
    echo "[postfix] Waiting for dovecot..."
    s6-svwait -U /run/s6/services/dovecot
fi

# Wait for syslog
echo "[postfix] Waiting for syslog..."
s6-svwait -U /run/s6/services/syslogd

# Start
echo "[postfix] Starting postfix..."
s6-notifyoncheck \
        -s 1000 \
        -t 1000 \
        -n 0 \
        -c "/usr/local/bin/check_postfix.sh" \
        /usr/sbin/postfix start-fg \
        2>&1 | awk -W Interactive '{print "[postfix] " $0}'
