version: '3.8'

services:
  mail_test:
    build:
      context: ../
    container_name: mail_test
    restart: always
    ports:
      - "2525:25"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      POSTMASTER_EMAIL: "postmaster@testdomain.tld"
      POSTFIX_INET_PROTOCOLS: "ipv4"
      POSTFIX_MYORIGIN: "mail.testdomain.tld"
      POSTFIX_MYDOMAIN: "testdomain.tld"
      POSTFIX_MYHOSTNAME: "mail.testdomain.tld"
      POSTFIX_MAIL_NAME: "mail_test"
      POSTFIX_REJECT_UNKNOWN_SENDER_DOMAIN: false
      ENABLE_OPENDKIM: "true"
      OPENDKIM_MODE: "v"
      OPENDKIM_LOGRESULTS: "true"
      OPENDKIM_LOGWHY: "true"
      ENABLE_SPF: "true"
      ENABLE_CLAMAV: "true"
      CLAMAV_MILTER_REPORT_HOSTNAME: "testdomain.tld"
      ENABLE_POSTGREY: "true"
    volumes:
      - ./tables_in:/etc/postfix/tables:ro
      - ./aliases_in:/etc/postfix/local_aliases:ro
